export const languages = [
  {code: "ab", name: "Abkhazian"},
  {code: "aa", name: "Afar"},
  {code: "af", name: "Afrikaans"},
  {code: "ak", name: "Akan"},
  {code: "sq", name: "Albanian"},
  {code: "am", name: "Amharic"},
  {code: "ar", name: "Arabic"},
  {code: "an", name: "Aragonese"},
  {code: "hy", name: "Armenian"},
  {code: "as", name: "Assamese"},
  {code: "av", name: "Avaric"},
  {code: "bh", name: "Bihari languages"},
  {code: "bi", name: "Bislama"},
  {code: "bs", name: "Bosnian"},
  {code: "br", name: "Breton"},
  {code: "bg", name: "Bulgarian"},
  {code: "my", name: "Burmese"},
  {code: "ca", name: "Catalan, Valencian"},
  {code: "km", name: "Central Khmer"},
  {code: "ch", name: "Chamorro"},
  {code: "ce", name: "Chechen"},
  {code: "ny", name: "Chichewa, Chewa, Nyanja"},
  {code: "zh", name: "Chinese"},
  {code: "cu", name: "Church Slavonic, Old Bulgarian, Old Church Slavonic"},
  {code: "cv", name: "Chuvash"},
  {code: "kw", name: "Cornish"},
  {code: "co", name: "Corsican"},
  {code: "cr", name: "Cree"},
  {code: "hr", name: "Croatian"},
  {code: "cs", name: "Czech"},
  {code: "da", name: "Danish"},
  {code: "dv", name: "Divehi, Dhivehi, Maldivian"},
  {code: "nl", name: "Dutch, Flemish"},
  {code: "dz", name: "Dzongkha"},
  {code: "en", name: "English"},
  {code: "eo", name: "Esperanto"},
  {code: "et", name: "Estonian"},
  {code: "ee", name: "Ewe"},
  {code: "fo", name: "Faroese"},
  {code: "fj", name: "Fijian"},
  {code: "fi", name: "Finnish"},
  {code: "fr", name: "French"},
  {code: "ff", name: "Fulah"},
  {code: "gd", name: "Gaelic, Scottish Gaelic"},
  {code: "gl", name: "Galician"},
  {code: "lg", name: "Ganda"},
  {code: "ka", name: "Georgian"},
  {code: "de", name: "German"},
  {code: "ki", name: "Gikuyu, Kikuyu"},
  {code: "el", name: "Greek (Modern)"},
  {code: "kl", name: "Greenlandic, Kalaallisut"},
  {code: "gn", name: "Guarani"},
  {code: "gu", name: "Gujarati"},
  {code: "ht", name: "Haitian, Haitian Creole"},
  {code: "ha", name: "Hausa"},
  {code: "he", name: "Hebrew"},
  {code: "hz", name: "Herero"},
  {code: "hi", name: "Hindi"},
  {code: "ho", name: "Hiri Motu"},
  {code: "hu", name: "Hungarian"},
  {code: "is", name: "Icelandic"},
  {code: "io", name: "Ido"},
  {code: "ig", name: "Igbo"},
  {code: "id", name: "Indonesian"},
  {
    code: "ia",
    name: "Interlingua (International Auxiliary Language Association)"
  },
  {code: "ie", name: "Interlingue"},
  {code: "iu", name: "Inuktitut"},
  {code: "ik", name: "Inupiaq"},
  {code: "rw", name: "Kinyarwanda"},
  {code: "kv", name: "Komi"},
  {code: "kg", name: "Kongo"},
  {code: "ko", name: "Korean"},
  {code: "kj", name: "Kwanyama, Kuanyama"},
  {code: "ku", name: "Kurdish"},
  {code: "ky", name: "Kyrgyz"},
  {code: "lo", name: "Lao"},
  {code: "la", name: "Latin"},
  {code: "lv", name: "Latvian"},
  {code: "lb", name: "Letzeburgesch, Luxembourgish"},
  {code: "li", name: "Limburgish, Limburgan, Limburger"},
  {code: "ln", name: "Lingala"},
  {code: "lt", name: "Lithuanian"},
  {code: "lu", name: "Luba-Katanga"},
  {code: "mk", name: "Macedonian"},
  {code: "mg", name: "Malagasy"},
  {code: "ms", name: "Malay"},
  {code: "ml", name: "Malayalam"},
  {code: "mt", name: "Maltese"},
  {code: "gv", name: "Manx"},
  {code: "mi", name: "Maori"},
  {code: "mr", name: "Marathi"},
  {code: "mh", name: "Marshallese"},
  {code: "ro", name: "Moldovan, Moldavian, Romanian"},
  {code: "mn", name: "Mongolian"},
  {code: "na", name: "Nauru"},
  {code: "nv", name: "Navajo, Navaho"},
  {code: "nd", name: "Northern Ndebele"},
  {code: "ng", name: "Ndonga"},
  {code: "ne", name: "Nepali"},
  {code: "se", name: "Northern Sami"},
  {code: "no", name: "Norwegian"},
  {code: "nb", name: "Norwegian Bokmål"},
  {code: "nn", name: "Norwegian Nynorsk"},
  {code: "ii", name: "Nuosu, Sichuan Yi"},
  {code: "oc", name: "Occitan (post 1500)"},
  {code: "oj", name: "Ojibwa"},
  {code: "or", name: "Oriya"},
  {code: "om", name: "Oromo"},
  {code: "os", name: "Ossetian, Ossetic"},
  {code: "pi", name: "Pali"},
  {code: "pa", name: "Panjabi, Punjabi"},
  {code: "ps", name: "Pashto, Pushto"},
  {code: "fa", name: "Persian"},
  {code: "pl", name: "Polish"},
  {code: "pt", name: "Portuguese"},
  {code: "qu", name: "Quechua"},
  {code: "rm", name: "Romansh"},
  {code: "rn", name: "Rundi"},
  {code: "ru", name: "Russian"},
  {code: "sm", name: "Samoan"},
  {code: "sg", name: "Sango"},
  {code: "sa", name: "Sanskrit"},
  {code: "sc", name: "Sardinian"},
  {code: "sr", name: "Serbian"},
  {code: "sn", name: "Shona"},
  {code: "sd", name: "Sindhi"},
  {code: "si", name: "Sinhala, Sinhalese"},
  {code: "tg", name: "Tajik"},
  {code: "ta", name: "Tamil"},
  {code: "tt", name: "Tatar"},
  {code: "te", name: "Telugu"},
  {code: "th", name: "Thai"},
  {code: "bo", name: "Tibetan"},
  {code: "ti", name: "Tigrinya"},
  {code: "to", name: "Tonga (Tonga Islands)"},
  {code: "ts", name: "Tsonga"},
  {code: "tn", name: "Tswana"},
  {code: "tr", name: "Turkish"},
  {code: "tk", name: "Turkmen"},
  {code: "tw", name: "Twi"},
  {code: "ug", name: "Uighur, Uyghur"},
  {code: "uk", name: "Ukrainian"},
  {code: "ur", name: "Urdu"},
  {code: "uz", name: "Uzbek"},
  {code: "ve", name: "Venda"},
  {code: "vi", name: "Vietnamese"},
  {code: "vo", name: "Volap_k"},
  {code: "wa", name: "Walloon"},
  {code: "cy", name: "Welsh"},
  {code: "fy", name: "Western Frisian"},
  {code: "wo", name: "Wolof"},
  {code: "xh", name: "Xhosa"},
  {code: "yi", name: "Yiddish"},
  {code: "yo", name: "Yoruba"},
  {code: "za", name: "Zhuang, Chuang"},
  {code: "zu", name: "Zulu"}
]

export const products = [
  "askgamblers.com",
  "latestbettingssites.co.uk",
  "parissportiff.com",
  "johnslots.com"
]

export const brands = ["Bet365", "Betway", "LeoVegas"]

export const pages = ["None", "Homepage", "Live Odds", "Live Casino", "News"]

export const sources = ["Web", "Instagram", "Facebook", "Youtube"]

export const placements = ["General", "Above the fold", "Toplist", "Footer"]

export const welcomeOffers = ["Bet & Get", "Commodities", "Exclusive"]

export const areas = ["Bingo", "Casino", "Sports", "ESports", "Lottery"]

export const markets = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands"
]
